export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const FETCH_ALL = 'FETCH_ALL'

export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const UPDATE_USER = 'UPDATE_USER'

export const FETCH_ALL_POST_CONTAINER = 'FETCH_ALL_POST_CONTAINER'
export const FETCH_CREATE_POST_CONTAINER = 'FETCH_CREATE_POST_CONTAINER'
export const FETCH_PHOTO_CONTAINER_CARD = 'FETCH_PHOTO_CONTAINER_CARD'